[package]
name = "scc050-t2"
version = "0.1.0"
authors = ["Gabriel Fontes <eu@misterio.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
